server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost